services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=traintix'
      - 'MONGO_INITDB_ROOT_PASSWORD=${SPRING_DATA_MONGODB_PASSWORD}'
      - 'MONGO_INITDB_ROOT_USERNAME=${SPRING_DATA_MONGODB_USERNAME}'
    ports:
      -  '${SPRING_DATA_MONGODB_PORT}:27017'

